### ISSUE TITLE
Documenting the config macros

### ISSUE THREAD

**Issue by xparq** [DreamyCecil/ZipLib#2]
_(Hey, nice fork! :) I'm also tinkering with [a version](https://github.com/xparq/ZipLib/), which I'm probably gonna base on yours, but with slightly different priorities, so perhaps not for merging back.)_ 

I'm using makefiles for CLI builds (similar to [Beneš](https://bitbucket.org/wbenny/)'s original), and it took me a while to figure out why the example didn't compile. Just defining them directly in `Main.cpp` "fixed" it:

    #define ZIPLIB_ZLIB
    #define ZIPLIB_BZIP2
    #define ZIPLIB_LZMA

but it would be nice to have them mentioned in the README specifically.

**Comment by DreamyCecil** [comment]
Thanks for the tip. Sample projects should build properly now.

Though I didn't touch CMake files since I don't know how to use them.

**Comment by xparq** [comment]
That was quick! :) 

> Though I didn't touch CMake files since I don't know how to use them.

Hehe, my version will probably not even have CMake support at all, as I don't know how to use them either! :)
