### ISSUE TITLE
Password test looking incorrect

### ISSUE THREAD

**Issue by xparq** [DreamyCecil/ZipLib#3]
I've built the test executable with MSVC, GCC on w64devkit, and CLANG on WSL2, and they all give this result

    [*] == Sample_ZipArchive_Decompress_Password_Protected ==
    [+] Extracting file 'in3.txt'
    [+] Trying no pass...
    [+] Trying wrong pass...
    [+] Trying correct password...
    [+] Content of a file: 'BZh61AY&SY����'

as opposed to the original BitBucket version's

    ...
    [+] Trying correct password...
    [+] Content of a file: 'Content to add'

Any idea why that could be?

**Comment by DreamyCecil** [comment]
Either another bug or some issues/pull requests changed the internal behavior, I'll look into it.

**Comment by xparq** [comment]
Yeah, looks like a regression to me.

**Comment by DreamyCecil** [comment]
Tried building the latest commit before any of my changes ( 176e4b6d51fc913fc7f7fb44df8f946374dc2c0c ) and the current one ( 5cfcb22201d01dc7b4c38bb33bd33ea1ac1478d9 ) using Visual Studio project files and both output it correctly: `'Content to add'`.

I don't have access to other compilers, so I can only assume it could be some kind of issue with encodings.

**Comment by xparq** [comment]
Thanks for looking into it!

Weird. The fact that it fails so consistently here with 3 totally different toolchains (all fairly up-to-date) indicates that it's not the compilers, but either my simple build proc, or somehow the system itself (albeit that's just a vanilla Win10/64, nothing funky).

I'll try to narrow it down.

_(I did something to my VS setup the other day and it had crapped itself, so I don't have a working VS IDE at the moment (even reinstalling failed :-o ), so can't try the "canonical" build here, unfortunately. The CLI is still fine, and that's what I mostly use anyway.)_

**Comment by xparq** [comment]
Ahh, wait a minute!... :) You know what the BZip2 magic sig. is?

    BZh

And its block header?

    1AY&SY

:-ooo :)

So... Any idea what could cause this failure of decompression (or accidental extra compression) there?

This is the prelude of `Main.cpp`, with the hack of adding all the cfg. defines at the top. (Can that, or the fact that they have _not_ been defined for compiling the lib cause any issues?)

    #define ZIPLIB_ZLIB
    #define ZIPLIB_BZIP2
    #define ZIPLIB_LZMA
    
    #ifdef _MSC_VER
    #define _CRTDBG_MAP_ALLOC
    #include <stdlib.h>
    #include <crtdbg.h>
    #endif
    
    #include "../ZipLib/ZipFile.h"
    #include "../ZipLib/streams/memstream.h"
    
    #include "../ZipLib/methods/Bzip2Method.h"
    
    #include <fstream>

**Comment by xparq** [comment]
> Can that, or the fact that they have not been defined for compiling the lib cause any issues?

Umm, OK, so the answer is yes! :)

I suggest slightly modifying the new note in the README from

    Define any of these macros before including ZipLib headers:

to

    Define any of these macros before including the ZipLib headers (also when building ZipLib itself):

if you think that could be helpful.

Albeit allowing to enable/disable features selectively for an app, regardless of how the lib was built (apart from the selectable features compiled in, of course), would be preferable, so the lib and the app builds are not coupled this way.

**Comment by DreamyCecil** [comment]
Yeah, I don't like this either but I do like giving options for the resulting library. Maybe I should remove them altogether, since all the modules are included with it anyway.

**Comment by DreamyCecil** [comment]
Just ended up inverting the macro checks, so everything is enabled by default. Hope this helps.

**Comment by xparq** [comment]
Yes, I was just about to write that I'd save the current state in a feature branch allowing it to possibly evolve later, and then remove it from the main branch to reduce complexity/confusion.

On the long run, feature selection would still be useful (e.g. I'm secretly hoping to support zstandard later, too, and I don't want app bloat -- while lib bloat is kinda OK), but with a more flexible design then.

Thanks! This can be closed now.
